### ISSUE TITLE
Error when loading library in certain browsers

### ISSUE THREAD

**Issue by tsadykhov** [nlp-compromise/nlp_compromise#106]
This can be reproduced by visiting the demo site in Firefox (I am running 45.0.2 but I was able to reproduce in 44, 43, etc.) or Safari (running 9.1 also doesn't work in 9.0)

Firefox is throwing the error: <code>TypeError: inf.endsWith is not a function</code>

Let me know if you need anything else.

**Comment by spencermountain** [comment]
ahh TImur, thanks!
will get that today

**Comment by spencermountain** [comment]
got it, v4.8.2
thanks man
